Removed quotes from variable type so it's compatible with Terraform 0.12
cloudposse/terraform-aws-ses-lambda-forwarder pull request #14
Opened 2019-12-11 23:02 UTC by tyd

Fixed the example in the README.yaml and generated README.md

2019-12-22 06:00 UTC, aknysh commented on README.yaml
> +    type = map
```suggestion
    type = map(list(string))
```

2019-12-22 06:01 UTC, aknysh requested changes
thanks @tyd 
Please see comments and please rebuild README by executing:

```
make init
make readme/deps
make readme
```

2019-12-23 18:24 UTC, tyd commented
@aknysh Thanks, the suggested change has been applied and the README.md generated based on the make instructions.

2019-12-23 18:47 UTC, aknysh commented
/codefresh run test

2019-12-23 19:04 UTC, aknysh approved these changes
thanks @tyd

2019-12-23 19:04 UTC, merged